import { FormEvent, useEffect, useState } from 'react'
import { api, saveToken, token } from './api'
import type { Location, Seat, Trip, User } from './types'

type Page='search'|'tracking'|'trips'|'support'|'operations'|'login'
const money=(v:number)=>`৳${Number(v).toLocaleString('en-BD')}`
const when=(v:string)=>new Date(v).toLocaleString('en-BD',{dateStyle:'medium',timeStyle:'short'})

export default function App(){
 const [page,setPage]=useState<Page>('search'),[user,setUser]=useState<User|null>(null),[notice,setNotice]=useState(''),[lang,setLang]=useState('EN')
 useEffect(()=>{if(token())api.me().then(setUser).catch(()=>saveToken(null))},[])
 const go=(p:Page)=>{setPage(p==='operations'&&!user?'login':p);scrollTo({top:0,behavior:'smooth'})}
 return <div><header className="topbar"><button className="brand" onClick={()=>go('search')}><i>▰</i>BusBD <b>Intelligence</b></button><nav>{(['search','tracking','trips','support'] as Page[]).map(p=><button className={page===p?'active':''} onClick={()=>go(p)} key={p}>{p==='tracking'?'Live tracking':p==='trips'?'My trips':p[0].toUpperCase()+p.slice(1)}</button>)}</nav><div><button className="ghost" onClick={()=>setLang(lang==='EN'?'বাংলা':'EN')}>◎ {lang}</button><button className="dark" onClick={()=>go('operations')}><span className="dot"/>Operations</button></div></header>
 {notice&&<div className="notice" onClick={()=>setNotice('')}>{notice} ×</div>}
 {page==='search'&&<Search setNotice={setNotice} go={go}/>} {page==='tracking'&&<Tracking/>} {page==='trips'&&<Trips/>} {page==='support'&&<Support setNotice={setNotice}/>} {page==='login'&&<Login done={u=>{setUser(u);setPage('operations')}}/>} {page==='operations'&&user&&<Operations user={user} logout={()=>{saveToken(null);setUser(null);go('search')}}/>}
 <footer><div><b>BusBD Intelligence</b><p>Enterprise public transport infrastructure for Bangladesh.</p></div><div><a href="/swagger-ui.html">Swagger API</a><a href="/actuator/health">System health</a></div><small>Demo admin: admin@busbd.local / Admin123!</small></footer></div>
}

function Search({setNotice,go}:{setNotice:(s:string)=>void;go:(p:Page)=>void}){
 const [from,setFrom]=useState('Dhaka'),[to,setTo]=useState('Chattogram'),[count,setCount]=useState(1),[trips,setTrips]=useState<Trip[]>([]),[summary,setSummary]=useState<any>({}),[chosen,setChosen]=useState<Trip|null>(null)
 useEffect(()=>{api.summary().then(setSummary).catch(()=>0)},[])
 const find=async(e:FormEvent)=>{e.preventDefault();try{setTrips(await api.trips(from,to))}catch(x){setNotice((x as Error).message)}}
 return <><section className="hero"><svg viewBox="0 0 900 600"><path d="M-10 120C160 10 240 230 420 150S700 70 930 20"/><path d="M20 620C180 450 300 600 410 440S650 360 840 470"/></svg><div className="heroText"><span className="eyebrow">✦ Bangladesh moves smarter</span><h1>Every journey,<br/><em>intelligently connected.</em></h1><p>Search, book and track buses with secure seat locking, digital tickets and live fleet intelligence.</p><form onSubmit={find} className="searchBox"><Field label="From"><select value={from} onChange={e=>setFrom(e.target.value)}><Cities/></select></Field><button type="button" className="swap" onClick={()=>{setFrom(to);setTo(from)}}>⇄</button><Field label="To"><select value={to} onChange={e=>setTo(e.target.value)}><Cities/></select></Field><Field label="Passengers"><select value={count} onChange={e=>setCount(+e.target.value)}>{[1,2,3,4].map(n=><option key={n}>{n}</option>)}</select></Field><button className="lime">Search buses →</button></form></div><aside className="live"><span><i className="dot"/>LIVE GPS</span><h2>Green Line · GL-208</h2><p>Dhaka → Chattogram</p><div className="rail">●━━━━▰━━━━○</div><div className="row"><span>AI arrival</span><b>7:10 AM</b></div><div className="row"><span>Delay risk</span><b className="safe">Low</b></div><button onClick={()=>go('tracking')}>Open live tracking ↗</button></aside></section>
 <section className="stats"><Stat n={summary.districtsConnected||62} t="districts"/><Stat n={summary.verifiedOperators||2} t="operators"/><Stat n={summary.buses||3} t="managed buses"/><Stat n={`${summary.etaAccuracy||91}%`} t="ETA accuracy"/><span><i className="dot"/>Network healthy</span></section>
 <main className="content"><header><div><span className="eyebrow">Enterprise mobility</span><h2>{trips.length?`${from} to ${to}`:'Intelligence at every step'}</h2></div><p>{trips.length?`${trips.length} services found`:'Built for passengers, drivers, operators and administrators.'}</p></header>{trips.length?<div className="tripList">{trips.map((t,i)=><article className="trip" key={t.id}>{i===0&&<mark>Best match</mark>}<div className="logo">{t.operator.slice(0,2).toUpperCase()}</div><div><h3>{t.operator}</h3><p>{t.bus} · {t.coachType}</p></div><div><b>{when(t.departureTime)}</b><p>{t.origin} → {t.destination}</p></div><div className="tags"><span>{t.availableSeats} seats</span><span>{Math.round(t.delayRisk*100)}% risk</span></div><div className="price"><b>{money(t.fare)}</b><button onClick={()=>setChosen(t)}>Choose seats</button></div></article>)}</div>:<div className="features"><Feature i="⌁" h="Live route intelligence" p="GPS freshness, speed, route progress and anomaly signals."/><Feature i="▦" h="Protected booking" p="Temporary seat locks, mock payments and QR tickets."/><Feature i="✦" h="AI-ready operations" p="ETA, demand, delay and recommendation service."/></div>}</main>{chosen&&<Book trip={chosen} count={count} close={()=>setChosen(null)} setNotice={setNotice}/>}</>
}

function Book({trip,count,close,setNotice}:{trip:Trip;count:number;close:()=>void;setNotice:(s:string)=>void}){
 const [seats,setSeats]=useState<Seat[]>([]),[picked,setPicked]=useState<string[]>([]),[name,setName]=useState('Demo Passenger'),[email,setEmail]=useState('passenger@example.com'),[ticket,setTicket]=useState<any>(null)
 useEffect(()=>{api.seats(trip.id).then(x=>setSeats(x.seats)).catch(e=>setNotice(e.message))},[trip.id])
 const toggle=(s:Seat)=>{if(s.status!=='AVAILABLE')return;setPicked(x=>x.includes(s.number)?x.filter(v=>v!==s.number):x.length<count?[...x,s.number]:x)}
 const pay=async()=>{if(picked.length!==count)return setNotice(`Select exactly ${count} seat(s)`);try{const h=await api.hold(trip.id,picked,email);setTicket(await api.book({holdId:h.id,passengerName:name,passengerEmail:email,passengerPhone:'+8801700000000',paymentProvider:'MOCK'}))}catch(e){setNotice((e as Error).message)}}
 return <div className="shade"><section className="modal"><button className="x" onClick={close}>×</button>{ticket?<div className="success"><h1>✓</h1><h2>Booking confirmed</h2><p>Reference <b>{ticket.reference}</b></p><img src={ticket.qrCode}/><p>Seats {ticket.seats.join(', ')} · {money(ticket.totalAmount)}</p><button className="dark" onClick={close}>Done</button></div>:<><span className="eyebrow">Secure seat selection</span><h2>{trip.operator}</h2><p>{trip.origin} → {trip.destination} · {money(trip.fare)} each</p><div className="coach">{seats.map(s=><button key={s.number} className={`${s.status.toLowerCase()} ${picked.includes(s.number)?'picked':''}`} onClick={()=>toggle(s)}>{s.number}</button>)}</div><div className="formRow"><input value={name} onChange={e=>setName(e.target.value)}/><input value={email} onChange={e=>setEmail(e.target.value)}/><button className="dark" onClick={pay}>Mock pay {money(trip.fare*picked.length)}</button></div></>}</section></div>
}

function Tracking(){const [locs,setLocs]=useState<Location[]>([]);useEffect(()=>{const load=()=>api.locations().then(setLocs).catch(()=>0);load();const id=setInterval(load,5000);return()=>clearInterval(id)},[]);return <main className="page"><span className="eyebrow">Live control plane</span><h1>Passenger live tracking</h1><p>Five-second updates. WebSocket broadcasts are available at <code>/ws</code>.</p><div className="map"><svg viewBox="0 0 800 500"><path d="M100 80C250 170 280 270 420 300S620 370 720 450"/></svg>{locs.map((l,i)=><div className="bus" style={{left:`${20+i*20}%`,top:`${25+i*15}%`}} key={l.busId}>▰<small>{Math.round(l.speedKph)} km/h</small></div>)}<aside><b><i className="dot"/>LIVE FLEET</b>{locs.length?locs.map(l=><article key={l.busId}>Bus {l.busId.slice(0,8)}<span>{Math.round(l.speedKph)} km/h</span></article>):<p>GPS simulator is starting…</p>}</aside></div></main>}
function Trips(){const [ref,setRef]=useState(''),[b,setB]=useState<any>(null),[err,setErr]=useState('');const find=async(e:FormEvent)=>{e.preventDefault();try{setB(await api.booking(ref));setErr('')}catch(x){setErr((x as Error).message)}};return <main className="page narrow"><span className="eyebrow">Digital ticket wallet</span><h1>Find your trip</h1><form className="lookup" onSubmit={find}><input value={ref} onChange={e=>setRef(e.target.value.toUpperCase())} placeholder="BBD123456"/><button className="dark">Find</button></form>{err&&<p className="error">{err}</p>}{b&&<div className="ticket"><img src={b.qrCode}/><div><h2>{b.reference}</h2><p>{b.passengerName}</p><b>{b.seats.join(', ')} · {money(b.totalAmount)}</b></div></div>}</main>}
function Support({setNotice}:{setNotice:(s:string)=>void}){const [email,setEmail]=useState('passenger@example.com'),[message,setMessage]=useState('');const send=async(e:FormEvent)=>{e.preventDefault();try{await api.complaint({email,category:'General support',message});setMessage('');setNotice('Support case submitted.')}catch(x){setNotice((x as Error).message)}};return <main className="page narrow"><span className="eyebrow">Passenger care</span><h1>How can we help?</h1><form className="support" onSubmit={send}><input value={email} onChange={e=>setEmail(e.target.value)}/><textarea value={message} onChange={e=>setMessage(e.target.value)} placeholder="Describe the issue"/><button className="dark">Submit case</button></form></main>}
function Login({done}:{done:(u:User)=>void}){const [email,setEmail]=useState('admin@busbd.local'),[pw,setPw]=useState('Admin123!'),[err,setErr]=useState('');const submit=async(e:FormEvent)=>{e.preventDefault();try{const r=await api.login(email,pw);saveToken(r.token);done(r.user)}catch(x){setErr((x as Error).message)}};return <main className="login"><form onSubmit={submit}><span className="eyebrow">Role-based access</span><h1>Operations sign in</h1><input value={email} onChange={e=>setEmail(e.target.value)}/><input type="password" value={pw} onChange={e=>setPw(e.target.value)}/>{err&&<p className="error">{err}</p>}<button className="dark">Sign in</button></form></main>}
function Operations({user,logout}:{user:User;logout:()=>void}){const [o,setO]=useState<any>({}),[buses,setBuses]=useState<any[]>([]),[books,setBooks]=useState<any[]>([]),[cases,setCases]=useState<any[]>([]);useEffect(()=>{Promise.all([api.overview(),api.buses(),api.bookings(),api.complaints()]).then(([a,b,c,d])=>{setO(a);setBuses(b);setBooks(c);setCases(d)})},[]);return <main className="page opsPage"><header><div><span className="eyebrow">National operations console</span><h1>Good day, {user.name}</h1><p>{user.role.replaceAll('_',' ')}</p></div><button className="ghost" onClick={logout}>Sign out</button></header><div className="kpis">{[['Fleet',o.buses],['Drivers',o.drivers],['Trips',o.trips],['Bookings',o.bookings],['Revenue',money(o.revenue||0)],['Open cases',o.openComplaints]].map(x=><article key={x[0]}><span>{x[0]}</span><b>{x[1]||0}</b></article>)}</div><div className="panels"><section><h2>Fleet health</h2>{buses.map(x=><div className="line" key={x.id}><span>{x.registrationNumber}</span><b>{x.healthScore}%</b></div>)}</section><section><h2>Recent bookings</h2>{books.map(x=><div className="line" key={x.id}><span>{x.reference}</span><b>{money(x.totalAmount)}</b></div>)}</section><section><h2>Support queue</h2>{cases.map(x=><div className="line" key={x.id}><span>{x.aiClassification}: {x.passengerEmail}</span><b>{x.status}</b></div>)}</section></div></main>}
function Field({label,children}:{label:string;children:any}){return <label><span>{label}</span>{children}</label>};function Cities(){return <>{['Dhaka','Chattogram','Sylhet','Rajshahi',"Cox's Bazar"].map(x=><option key={x}>{x}</option>)}</>};function Stat({n,t}:{n:any;t:string}){return <div><b>{n}</b><span>{t}</span></div>};function Feature({i,h,p}:{i:string;h:string;p:string}){return <article><i>{i}</i><h3>{h}</h3><p>{p}</p></article>}
